import { c as create_ssr_component } from "../../../chunks/hooks.js";
const css = {
  code: ".intro.svelte-1owwzaz.svelte-1owwzaz{margin-bottom:1.5rem;font-size:1.05rem}.research-item.svelte-1owwzaz.svelte-1owwzaz{margin-bottom:1.5rem}.research-item.svelte-1owwzaz h3.svelte-1owwzaz{font-size:1.2rem;margin-bottom:0.25rem;text-align:left}hr.svelte-1owwzaz.svelte-1owwzaz{margin:2rem 0;border:none;border-top:1px solid var(--color-bg-0)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1i9ytao_START -->${$$result.title = `<title>Research</title>`, ""}<meta name="description" content="Research - AI and Quantum Computing"><!-- HEAD_svelte-1i9ytao_END -->`, ""}

<div class="text-column"><h1>Research</h1>
	<p class="intro svelte-1owwzaz">I work on problems that bridge theoretical foundations with practical systems, with a focus on AI and quantum computing.
	</p>

	
	<h2 class="section-header">AI Research</h2>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Mechanistic Interpretability</h3>
		<span class="tag">Interpretability / Safety</span>
		<p>Developing methods to understand what neural networks learn.
			My <a href="/musings/sensitive-features">sensitivity-based feature discovery</a> work
			proposes alternatives to sparse autoencoders that explain feature sparsity without requiring it as an assumption.
		</p></div>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Formal Proofs for Transformers</h3>
		<span class="tag">ML Theory</span>
		<p>Proving formal statements about transformer behavior given their weights.
			Leveraging techniques from verification and formal methods to make rigorous claims about specific neural network computations.
		</p></div>

	<hr class="svelte-1owwzaz">

	
	<h2 class="section-header">Quantum Cryptography &amp; Computing</h2>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">One-Time Programs &amp; Quantum Cryptography</h3>
		<span class="tag">Quantum Crypto</span>
		<p>Building cryptographic primitives from physics rather than computational assumptions.
			Recent work includes verifiable one-time programs enabling single-round secure computation
			(<a href="https://arxiv.org/abs/2509.22290">arXiv</a>),
			constructions without long-term quantum memory
			(<a href="https://arxiv.org/abs/2504.21842">arXiv</a>),
			information-theoretic security from geometrically local adversaries
			(<a href="https://arxiv.org/abs/2503.22016">arXiv</a>),
			and one-time memories from stateless hardware
			(<a href="https://arxiv.org/abs/2501.04168">arXiv</a>).
		</p></div>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Depth Bounded Quantum Cryptography</h3>
		<span class="tag">Quantum Crypto</span>
		<p>Exploring how quantum cryptography becomes more powerful when adversaries have limited quantum resources — a realistic model for near-term security.
		</p></div>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Quantum Error Correction</h3>
		<span class="tag">Quantum Computing</span>
		<p>Work on weight-reduced codes, hypergraph products, and improved decoding algorithms.
			Includes effective distance preservation for weight reduced codes (<a href="https://arxiv.org/abs/2409.02193">arXiv</a>)
			and improved Small-Set-Flip decoding presented at QIP 2024 (<a href="https://arxiv.org/abs/2311.00877">arXiv</a>).
		</p></div>

	<hr class="svelte-1owwzaz">

	
	<h2 class="section-header">Selected Past Work</h2>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Multiparty Secret Leader Election</h3>
		<span class="tag">Cryptography</span>
		<p>Work done while at the Ethereum Foundation with Mark Simkin to improve communication cost of secret leader election for multiple leaders.
			Resulted in a novel data independent and oblivious priority queue.
		</p></div>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">Weighted Secret Sharing from the Wiretap Channel</h3>
		<span class="tag">Information Theory</span>
		<p>With Fabrice Benhamouda and Shai Halevi, introduced a novel connection between weighted secret sharing and wiretap channels.
			Presented at Information-Theoretic Cryptography (ITC) 2023 (<a href="https://eprint.iacr.org/2022/1578.pdf">ePrint</a>).
		</p></div>

	<div class="research-item svelte-1owwzaz"><h3 class="svelte-1owwzaz">3D Turtles and Drawing Math</h3>
		<span class="tag">Math Visualization</span>
		<p>Explored whether movement sequences generated by rational numbers form closed paths.
			The closure question connects to discrete logs and specific multinomial roots.
			<a href="https://github.com/Lev-Stambler/3D-Turtles/blob/master/paper/Paper.pdf">Paper</a> |
			<a href="https://3dturtles.groked.co/">Interactive demo</a></p>
		<img style="justify-self: center; width: 100%; padding: 0 20%; box-sizing: border-box; margin-top: 1rem;" src="https://raw.githubusercontent.com/Lev-Stambler/3D-Turtles/master/curated-list/second.png" alt="3D Turtle visualization"></div>
</div>`;
});
export {
  Page as default
};
