<svelte:head>
	<title>Research</title>
	<meta name="description" content="Research" />
</svelte:head>

<div class="text-column current-research">
	<h1>Current Research Project</h1>

	<div class="research-item">
		<h2>Fully Homomorphic Encryption and Private Functions Commitments</h2>
		<p>
			Working with <a href="https://www.topology.gg/">Topology</a> to create a
			<a href="https://www.guiltygyoza.xyz/2022/11/double-blind">double blinding</a>
			protocol. Essentially, a computing party (Alice) knowns some function and a customer (Bob) wants
			to evaluate his input on this function. Alice does not want to reveal the function, and Bob does
			not want to reveal his input. But, Bob a proof that his input was evaluated on the promised function.
		</p>
	</div>
	<div class="research-item">
		<h2>Reinforcment Learning to Create Better Quantum Codes Under Various Noise Models</h2>
		<img
			src="https://img.shields.io/badge/Supported%20By-UNITARY%20FUND-brightgreen.svg?style=for-the-badge"
			alt="Unitary Fund Badge"
		/>
		<p>
			Received grant from the Unitary fund to create a decoding library for simulated noise. The
			noise will be simulated via <a href="https://github.com/quantumlib/Stim">Stim</a>. Further
			work includes using reinforcement learning to learn quantum LDPC codes with good performance.
		</p>
	</div>
	<div class="research-item">
		<h2>Quantum Error Correction, Hypergraph Product Codes, and Small Cycle Flip</h2>
		<p>
			Working with Anirudh Krishna and Michael Beverland to improve speed and decrease word error
			rates for
			<a href="https://arxiv.org/abs/1504.00822"
				>hypergraph product codes (also known as quantum expander codes).</a
			>
			We are wrapping up research and initial data suggests that we have achieved an order of magnitude decrease in word error rates over state
			of the art. We also introduce provably correct algorithmic changes which speed up the SSF decoder
			introduced in
			<a href="https://arxiv.org/abs/1504.00822"> the hypergraph product code paper</a> by 10-100x.
		</p>
	</div>
</div>

<hr />

<div class="text-column">
	<h1>Past Research</h1>
	<hr />
	<div class="research-item">
		<h2>Weighted Secret Sharing from the Wiretap Channel</h2>
		<p>
			With Fabrice Benhamouda and Shai Halevi, we introduced a novel connection between weighted
			secret sharing and wiretap channels. Achieving a ramped weighted secret sharing scheme, we
			eliminate dependence on the number of parties and use little public information. <a
				href="https://eprint.iacr.org/2022/1578">The preprint</a
			>
			can be found on ePrint.
		</p>
	</div>
	<div class="research-item">
		<h2>3D Turtles and Drawing Math</h2>
		<p>
			A fun side project, I explored whether a sequence of movements to an object generated by
			rational numbers will form a closed path. Surprisingly, the question of closure is initmatly
			connected to discrete logs and roots of a very specific multinomial with coefficients of +/-
			1. The paper can be found on <a
				href="https://github.com/Lev-Stambler/3D-Turtles/blob/master/paper/Paper.pdf">Github</a
			>. With a friend <a href="https://www.shivaperi.com/">(Shiva Peri)</a>, we also created a visualization which creates some rather beautiful shapes.
			We also posted an <a href="https://3dturtles.groked.co/">interactive website</a> to play around
			with parameters.
		</p>
		<img
			style="justify-self: center; width: 100%; padding: 0 20%; box-sizing: border-box;"
			src="https://raw.githubusercontent.com/Lev-Stambler/3D-Turtles/master/curated-list/second.png"
			alt=""
		/>
	</div>
</div>

<style>
	.research-item h2 {
		font-size: 1.3rem;
	}
</style>
